### ISSUE TITLE
Miscellaneous bugfixes

### ISSUE THREAD

**Issue by dloscutoff** [somebody1234/Charcoal#1]
- <s>`ＵＢ` leaves old background characters in areas of canvas left of printed content</s>
- Refactor `Charcoal.__str__`
- <s>`CleanExecute` should take varargs</s>
- Some prints have an extra move at the end
- <s>`←abc↓def` has problems</s>
- Fill, when called on non-enclosed areas, should show an error message instead of dying on IndexError
- When printing leftward, `¶` should move the cursor up, not down

**Comment by somebody1234** [comment]
4 is intentional, 3 and 5 are fixed in mine as well, I've changed `__str__` so you'll have to re-refactor, 1 is fixed (thanks for finding that btw)
