### ISSUE TITLE
Unary operator aliases on wiki are incorrect

### ISSUE THREAD

**Issue by totallyhuman** [somebody1234/Charcoal#13]
The wiki currently says `++` is an alias for `Incremented` , `Decremented`, `Doubled` and `Halved`. (copy-paste error, I'm presuming :P)

> Operator | Verbose | Returns
> -- | -- | --
> ... | ... | ...
> ⊕ | `Incremented`/`++` | `x+1` if it is a number, ... if it is a string. Vectorizes.
> ⊖ | `Decremented`/`++` | `x-1` if it is a number, ... if it is a string. Vectorizes.
> ⊗ | `Doubled`/`++` | `x*2` if it is a number, ... if it is a string. Vectorizes.
> ⊘ | `Halved`/`++` | `x/2` if it is a number, ... if it is a string. Vectorizes.

According to [line 131 to 132 of verbosegrammars.py](https://github.com/somebody1234/Charcoal/blob/master/verbosegrammars.py#L131-L132), these should be `++`, `--`, `***` and `` \\ `` respectively.

<sub>Why isn't the wiki public? And why does Github have no sane way of reporting errors in the wiki?</sub>

**Comment by somebody1234** [comment]
Oops, sent invite because I'm too lazy to do it myself
