### ISSUE TITLE
Design decisions

### ISSUE THREAD

**Issue by somebody1234** [somebody1234/Charcoal#3]
- What should happen when `RotateCopy` is passed an odd number of rotations (currently errors)
- How should separate inputs be separated? Do we assume all input strings are single-line?
- Do we allow multiline string input?

**Comment by dloscutoff** [comment]
- Where should the cursor be after rotations and reflections? (Try `abc⟲⁴x`, e.g.)

**Comment by somebody1234** [comment]
@dloscutoff IMO it shouldn't move, else it gets translated with the canvas

**Comment by somebody1234** [comment]
Moved to design doc on HackMD
