### ISSUE TITLE
Internal bug when handling quotes «»

### ISSUE THREAD

**Issue by MarSoft** [somebody1234/Charcoal#8]
Just tried to experiment with this unusual language. When the interpreter encounters opening quote `«` character, it crashes with a stack trace:
```
$ ./charcoal
Charcoal> «
Traceback (most recent call last):
  File "./charcoal", line 4670, in <module>
    normal_encoding=argv.normalencoding
  File "./charcoal", line 4082, in Run
    )(charcoal)
  File "/tmp/Charcoal/interpreterprocessor.py", line 358, in <lambda>
    lambda r: lambda c: ((r[0](c) or True) and r[2](c)),
  File "/tmp/Charcoal/interpreterprocessor.py", line 370, in <lambda>
    lambda r: lambda c: c.Print(r[0](c)),
  File "./charcoal", line 987, in Print
    lines = re.split("[\n\r]", string)
  File "/usr/lib/python3.6/re.py", line 212, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object
```

When encounters closing quote `»`, it just does nothing.

**Comment by somebody1234** [comment]
Oh yeah, that's supposed to be a lambda that does nothing (since Charcoal autocloses open double angle brackets) but that functionality has not been implemented yet :/

**Comment by somebody1234** [comment]
Fixed, will push once I add tests

**Comment by somebody1234** [comment]
Done, if you want to experiment with lambdas in other places/have suggestions on what they should do in other places feel free to reopen this issue or open another
